/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:6152ab19-d54f-4b97-bca8-3b95590e97e5",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_pwie9NkaL",
    "aws_user_pools_web_client_id": "7o56mhqpa9dhgb2o6u0lnket23",
    "oauth": {}
};


export default awsmobile;
