/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "us-east-2:6152ab19-d54f-4b97-bca8-3b95590e97e5",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_erLJm7tcF",
    "aws_user_pools_web_client_id": "4jkvlqg0eav0e98f76ok047a63",
    "oauth": {}
};


export default awsmobile;
